//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moving_Files {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class MovingFiles : global::System.Configuration.ApplicationSettingsBase {
        
        private static MovingFiles defaultInstance = ((MovingFiles)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MovingFiles())));
        
        public static MovingFiles Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\rvargas\\Desktop\\actualizador")]
        public string root_folder {
            get {
                return ((string)(this["root_folder"]));
            }
            set {
                this["root_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\rvargas\\Desktop\\actualizador\\new_version_folder")]
        public string new_version_folder {
            get {
                return ((string)(this["new_version_folder"]));
            }
            set {
                this["new_version_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\rvargas\\Desktop\\actualizador\\current_folder")]
        public string official_folder {
            get {
                return ((string)(this["official_folder"]));
            }
            set {
                this["official_folder"] = value;
            }
        }
    }
}
